import Sidebar from "components/Sidebar/Sidebar";
import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen max-w-7xl mx-auto">
        <Sidebar />
      </main>
    </div>
  );
}
